import type { MetadataRoute } from "next";

const BASE = "https://freelance-ua.agency";

const casePaths = [
  "/cases/it/eva-code",
  "/cases/it/ruslan-aviation",
  "/cases/it/repair-collision",
  "/cases/it/prime-auto-shipping",
  "/cases/it/asandra-soul",
  "/cases/it/liudmyla-tsybrii",
  "/cases/it/pivden-solar",
  "/cases/it/route-core",
  "/cases/it/serezha-shop",
  "/cases/it/nextcup",
  "/cases/it/shkiper-drop",
  "/cases/it/mnm-detailing",
  "/cases/it/sdent",
  "/cases/it/md-dental",
  "/cases/it/voltone-pro",
  "/cases/it/selloflow",
  "/cases/it/importera",
  "/cases/it/darkshare",
  "/cases/it/epiland",
  "/cases/design/hope-media-group",
  "/cases/design/nastya-smm",
  "/cases/design/vikontse-logo",
  "/cases/design/schonheit-gift-certificate",
  "/cases/design/smm-case-presentation",
  "/cases/design/mht-clinic-billboard",
  "/cases/design/prestige-school-billboard",
  "/cases/design/mydutyfree",
  "/cases/design/gopro-hero13",
  "/cases/design/gel-polish",
  "/cases/design/divorce-legal-ad",
  "/cases/design/giesbrecht-pv",
  "/cases/design/sembud-repair",
  "/cases/design/crypto-chat-manager-vacancy",
  "/cases/design/apple-tecnologia",
  "/cases/design/f5-guitars-youtube",
  "/cases/design/pink-pr-flyers",
  "/cases/design/photo-retouch",
  "/cases/design/nastya-portrait-retouch",
  "/cases/video/nikita-sheremet-crypto",
  "/cases/video/eva-code-reels",
  "/cases/video/dominanta-youtube-intro",
  "/cases/video/vtikha-promo",
  "/cases/video/yulia-smm-reels",
  "/cases/video/artem-reels",
  "/cases/video/vsehub-reels",
  "/cases/video/dance-competition-lviv",
  "/cases/video/auto-edits-reels",
  "/cases/video/vitalii-cheverda",
  "/cases/video/wine-festival",
  "/cases/video/cuprus-life",
  "/cases/video/veronika-ai-muscles",
  "/cases/video/ai-ice-cream",
  "/cases/video/sestro-beauty",
  "/cases/video/logan-ai-promo",
  "/cases/video/ivan-ig-creative",
  "/cases/video/alien-city-adventure",
  "/cases/video/sheglam-promo",
  "/cases/video/valeriia-trend-reels",
  "/cases/video/vibe-nation-promo",
  "/cases/video/ai-avatars",
  "/cases/video/sheglam-freedom-fest",
  "/cases/video/ai-promo-misha",
  "/cases/video/ai-spring-fashion",
  "/cases/video/vorodi-medical",
  "/cases/video/selloflow-intro",
  "/cases/video/motion-promo",
  "/cases/video/internet-svit-promo",
  "/cases/video/watch-hype-motion",
  "/cases/video/sales-bible-promo",
  "/cases/video/logo-animation",
  "/cases/video/presentation-animation",
  "/cases/video/motion-reels",
  "/cases/video/watch-hype-intro",
  "/cases/video/income-graph-motion",
  "/cases/video/telegram-emoji-stickers",
  "/cases/video/skool-10-features",
  "/cases/video/varto-reels",
  "/cases/video/vladlen-lisynko-interview",
  "/cases/video/podcast-editing",
  "/cases/video/automation-1click",
  "/cases/video/passive-income-video",
  "/cases/video/youtube-conversational-video",
  "/cases/video/liliya-product-business",
  "/cases/video/taranenko-trade",
];

export default function sitemap(): MetadataRoute.Sitemap {
  const now = new Date();

  const staticPages: MetadataRoute.Sitemap = [
    { url: `${BASE}/`, lastModified: now, changeFrequency: "monthly", priority: 1.0 },
    { url: `${BASE}/cases`, lastModified: now, changeFrequency: "weekly", priority: 0.9 },
    { url: `${BASE}/cases/it`, lastModified: now, changeFrequency: "weekly", priority: 0.8 },
    { url: `${BASE}/cases/design`, lastModified: now, changeFrequency: "weekly", priority: 0.8 },
    { url: `${BASE}/partners`, lastModified: now, changeFrequency: "monthly", priority: 0.7 },
  ];

  const casePages: MetadataRoute.Sitemap = casePaths.map((path) => ({
    url: `${BASE}${path}`,
    lastModified: now,
    changeFrequency: "monthly" as const,
    priority: 0.7,
  }));

  return [...staticPages, ...casePages];
}
